spring:
  application:
    name: multidatasource
  datasource:
    db1:
      jdbc-url: jdbc:mysql://47.95.238.195/zbx_miniprogram?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    db2:
      jdbc-url: jdbc:mysql://127.0.0.1/python?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      #注意jdbc-url和com.mysql.cj.jdbc.Driver
